apiVersion: v1
kind: Pod
metadata:
  name: po1
  labels:
    app: hello-jb
spec:
  containers:
  - name: k8s-demo
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config/proxy.conf  # Nginx default config path
      subPath: proxy.conf
      readOnly: true
  volumes:
  - name: secretvolume
    secret:
      secretName: db-secret
  - name: config-volume
    configMap:
      name: nginx-proxy