apiVersion: v1
kind: Pod
metadata:
  name: hello.jb-file
  labels:
    app: hello-jb
spec:
  containers:
  - name: k8s-demo
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: secretvolume
      mountPath: /etc/secretfiles ### files will be stored here
      readOnly: true
  volumes:
  - name: secretvolume
    secret:
      secretName: db-secret