apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.enviroment.name }}-deployment #from RELEASE NAME
spec:
  selector: 
    matchLabels:
      {{- include "spring.labels" . | nindent 6}}
  replicas: {{ .Values.deployment.replicas }}  #from values
  template:
    metadata:
      labels:
        {{- include "spring.labels" . | nindent 8}}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name}} #from values
        image: {{ .Values.deployment.container.image }}:{{ .Values.deployment.container.imageTag }} #from values
        ports:
        - containerPort: {{ .Values.deployment.container.port }}

---
kind: Service     
apiVersion: v1     
metadata:
  name: {{ .Values.enviroment.name }}-service #from RELEASE NAME
spec:
  selector:
    app: {{- include "spring.labels" . | nindent 4}}
  type: {{ .Values.deployment.type }}  #from values
  ports:         
  - name: http   
    protocol: TCP
    port: {{ .Values.Service }}
    targetPort: {{ .Values.service.port }}